# .github/workflows/weekly-nfl-data-collection.yml
# Automated weekly NFL data collection using nfl_data_py

name: Weekly NFL Data Collection

on:
  schedule:
    # Run every Tuesday at 6:00 AM UTC (before waivers process)
    - cron: '0 6 * * 2'
  workflow_dispatch:  # Allow manual triggers

jobs:
  collect-nfl-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nfl_data_py pandas requests
        
    - name: Run NFL data collection
      run: |
        python scripts/collect_nfl_data.py
        
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
    - name: Commit and push changes
      run: |
        git add json_data/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Weekly NFL data update - $(date +'%Y-%m-%d')"
          git push
        fi
